Repository Re-logging/server, pull requests merged in 2024-11, with the labels that each got.

#64 feat: reissue
  src/main/kotlin/com/relogging/server/global/exception/GlobalErrorCode.kt
  src/main/kotlin/com/relogging/server/redis/service/RefreshTokenService.kt
  src/main/kotlin/com/relogging/server/redis/service/RefreshTokenServiceImpl.kt
  src/main/kotlin/com/relogging/server/security/controller/AuthController.kt
  src/main/kotlin/com/relogging/server/security/jwt/provider/TokenProvider.kt
  src/main/kotlin/com/relogging/server/security/oauth/handler/OAuthAuthenticationSuccessHandler.kt
  src/main/kotlin/com/relogging/server/security/service/AuthService.kt
  src/main/kotlin/com/relogging/server/security/service/AuthServiceImpl.kt
  src/main/kotlin/com/relogging/server/security/service/PrincipalDetailsService.kt
Labels: feat

#65 Feat/61 comment
  src/main/kotlin/com/relogging/server/domain/comment/controller/PloggingEventCommentController.kt
  src/main/kotlin/com/relogging/server/domain/comment/controller/PloggingMeetupCommentController.kt
  src/main/kotlin/com/relogging/server/domain/comment/dto/CommentConverter.kt
  src/main/kotlin/com/relogging/server/domain/comment/dto/CommentRequest.kt
  src/main/kotlin/com/relogging/server/domain/comment/dto/CommentResponse.kt
  src/main/kotlin/com/relogging/server/domain/comment/entity/Comment.kt
  src/main/kotlin/com/relogging/server/domain/comment/repository/CommentRepository.kt
  src/main/kotlin/com/relogging/server/domain/comment/service/PloggingEventCommentService.kt
  src/main/kotlin/com/relogging/server/domain/comment/service/PloggingEventCommentServiceImpl.kt
  src/main/kotlin/com/relogging/server/domain/comment/service/PloggingMeetupCommentService.kt
  src/main/kotlin/com/relogging/server/domain/comment/service/PloggingMeetupCommentServiceImpl.kt
  src/main/kotlin/com/relogging/server/domain/crew/controller/CrewController.kt
  src/main/kotlin/com/relogging/server/domain/crew/entity/Crew.kt
  src/main/kotlin/com/relogging/server/domain/crew/entity/CrewMember.kt
  src/main/kotlin/com/relogging/server/domain/crew/service/CrewService.kt
  src/main/kotlin/com/relogging/server/domain/crew/service/CrewServiceImpl.kt
  src/main/kotlin/com/relogging/server/domain/plogging/controller/PloggingEventController.kt
  src/main/kotlin/com/relogging/server/domain/plogging/dto/PloggingEventConverter.kt
  src/main/kotlin/com/relogging/server/domain/plogging/dto/PloggingEventResponse.kt
  src/main/kotlin/com/relogging/server/domain/plogging/entity/PloggingEvent.kt
  src/main/kotlin/com/relogging/server/domain/plogging/service/PloggingEventService.kt
  src/main/kotlin/com/relogging/server/domain/plogging/service/PloggingEventServiceImpl.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/controller/PloggingMeetupController.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/dto/PloggingMeetupConverter.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/dto/PloggingMeetupResponse.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/entity/PloggingMeetup.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/service/PloggingMeetupService.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/service/PloggingMeetupServiceImpl.kt
  src/main/kotlin/com/relogging/server/domain/user/entity/User.kt
  src/main/kotlin/com/relogging/server/global/config/JacksonConfig.kt
  src/main/kotlin/com/relogging/server/global/exception/ErrorResponse.kt
  src/main/kotlin/com/relogging/server/global/exception/GlobalErrorCode.kt
  src/main/kotlin/com/relogging/server/infrastructure/admin/controller/AdminController.kt
  src/main/kotlin/com/relogging/server/security/config/SecurityConfig.kt
  src/main/kotlin/com/relogging/server/security/handler/JwtAccessDeniedHandler.kt
  src/main/kotlin/com/relogging/server/security/handler/JwtAuthenticationEntryPoint.kt
Labels: feat

#67 feat: HttpCookieOAuth2AuthorizationRequestRepository
  src/main/kotlin/com/relogging/server/security/config/SecurityConfig.kt
  src/main/kotlin/com/relogging/server/security/oauth/repository/HttpCookieOAuth2AuthorizationRequestRepository.kt
  src/main/kotlin/com/relogging/server/security/util/CookieUtils.kt
Labels: feat

#68 Feat/60 image hosting
  .github/workflows/dev_ci_cd.yml
  .github/workflows/main_ci_cd.yml
  build.gradle.kts
  src/main/kotlin/com/relogging/server/domain/crew/service/CrewServiceImpl.kt
  src/main/kotlin/com/relogging/server/domain/image/service/ImageService.kt
  src/main/kotlin/com/relogging/server/domain/image/service/ImageServiceImpl.kt
  src/main/kotlin/com/relogging/server/domain/newsArticle/service/NewsArticleServiceImpl.kt
  src/main/kotlin/com/relogging/server/domain/plogging/service/PloggingEventServiceImpl.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/service/PloggingMeetupServiceImpl.kt
  src/main/kotlin/com/relogging/server/global/config/AmazonConfig.kt
  src/main/kotlin/com/relogging/server/global/exception/GlobalErrorCode.kt
  src/main/kotlin/com/relogging/server/infrastructure/aws/s3/AmazonS3Service.kt
  src/main/resources/application.yml
Labels: feat

#69 [Fix] Feat/60 image hosting
  .github/workflows/dev_ci_cd.yml
  .github/workflows/main_ci_cd.yml
  src/main/kotlin/com/relogging/server/infrastructure/aws/s3/AmazonS3Service.kt
  src/main/resources/application.yml
Labels: fix

#71 feat: 1365 api fetch data
  .github/workflows/dev_ci_cd.yml
  .github/workflows/main_ci_cd.yml
  build.gradle.kts
  src/main/kotlin/com/relogging/server/domain/plogging/controller/PloggingEventController.kt
  src/main/kotlin/com/relogging/server/domain/plogging/service/PloggingEventService.kt
  src/main/kotlin/com/relogging/server/domain/plogging/service/PloggingEventServiceImpl.kt
  src/main/kotlin/com/relogging/server/global/config/WebClientConfig.kt
  src/main/resources/application.yml
Labels: feat

#72 refactor: OAuth
  src/main/kotlin/com/relogging/server/domain/user/dto/UserResponse.kt
  src/main/kotlin/com/relogging/server/domain/user/entity/User.kt
  src/main/kotlin/com/relogging/server/global/util/CookieUtils.kt
  src/main/kotlin/com/relogging/server/security/config/SecurityConfig.kt
  src/main/kotlin/com/relogging/server/security/controller/AuthController.kt
  src/main/kotlin/com/relogging/server/security/dto/OAuthLoginRequest.kt
  src/main/kotlin/com/relogging/server/security/dto/OAuthLoginResponse.kt
  src/main/kotlin/com/relogging/server/security/oauth/repository/HttpCookieOAuth2AuthorizationRequestRepository.kt
  src/main/kotlin/com/relogging/server/security/service/AuthService.kt
  src/main/kotlin/com/relogging/server/security/service/AuthServiceImpl.kt
  src/main/resources/application.yml
Labels: refactor

#78 Refactor/76 file dir and scheduler
  build.gradle.kts
  src/main/kotlin/com/relogging/server/domain/crew/controller/CrewController.kt
  src/main/kotlin/com/relogging/server/infrastructure/admin/controller/AdminController.kt
  src/main/kotlin/com/relogging/server/infrastructure/crawling/service/CrawlingService.kt
  src/main/kotlin/com/relogging/server/infrastructure/crawling/service/PloggingEventCrawlingServiceImpl.kt
  src/main/kotlin/com/relogging/server/infrastructure/redis/entity/RefreshToken.kt
  src/main/kotlin/com/relogging/server/infrastructure/redis/repository/RefreshTokenRepository.kt
  src/main/kotlin/com/relogging/server/infrastructure/redis/service/RefreshTokenService.kt
  src/main/kotlin/com/relogging/server/infrastructure/redis/service/RefreshTokenServiceImpl.kt
  src/main/kotlin/com/relogging/server/infrastructure/scheduler/NewsArticleScrapingScheduler.kt
  src/main/kotlin/com/relogging/server/infrastructure/scraping/service/NewsArticleNewsArticleScrapingServiceImpl.kt
  src/main/kotlin/com/relogging/server/infrastructure/scraping/service/NewsArticleScrapingService.kt
  src/main/kotlin/com/relogging/server/security/controller/AuthController.kt
  src/main/kotlin/com/relogging/server/security/oauth/handler/OAuthAuthenticationSuccessHandler.kt
  src/main/kotlin/com/relogging/server/security/service/AuthServiceImpl.kt
Labels: refactor

#80 fix: 플로깅 모임 생성 시 이미지 안넣었을 때 오류 처리
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/controller/PloggingMeetupController.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/dto/PloggingMeetupRequest.kt
Labels: fix

#81 Fix/59 hotfix
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/controller/PloggingMeetupController.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/dto/PloggingMeetupRequest.kt
Labels: fix

#82 fix: 환경변수 오류처리
  .github/workflows/dev_ci_cd.yml
Labels: fix

#84 Fix/83 400번대 에러 핸들링 수정
  src/main/kotlin/com/relogging/server/global/exception/ErrorResponse.kt
  src/main/kotlin/com/relogging/server/global/exception/GlobalExceptionAdvice.kt
  src/main/kotlin/com/relogging/server/security/config/SecurityConfig.kt
Labels: fix

#85 Refactor/increase hits
  src/main/kotlin/com/relogging/server/domain/newsArticle/controller/NewsArticleController.kt
  src/main/kotlin/com/relogging/server/domain/newsArticle/service/NewsArticleService.kt
  src/main/kotlin/com/relogging/server/domain/newsArticle/service/NewsArticleServiceImpl.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/service/PloggingMeetupServiceImpl.kt
Labels: refactor

#86 Feat/77 plogging event
  src/main/kotlin/com/relogging/server/domain/plogging/dto/PloggingEventConverter.kt
  src/main/kotlin/com/relogging/server/domain/plogging/dto/PloggingEventRequest.kt
  src/main/kotlin/com/relogging/server/domain/plogging/entity/PloggingEvent.kt
  src/main/kotlin/com/relogging/server/domain/plogging/repository/PloggingEventRepository.kt
  src/main/kotlin/com/relogging/server/domain/plogging/service/PloggingEventService.kt
  src/main/kotlin/com/relogging/server/domain/plogging/service/PloggingEventServiceImpl.kt
  src/main/kotlin/com/relogging/server/infrastructure/admin/controller/AdminController.kt
  src/main/kotlin/com/relogging/server/infrastructure/scheduler/PloggingEventScheduler.kt
  src/main/kotlin/com/relogging/server/infrastructure/scraping/service/PloggingEventScrapingService.kt
  src/main/kotlin/com/relogging/server/infrastructure/scraping/service/PloggingEventScrapingServiceImpl.kt
Labels: feat

#88 feat: plogging event increasing hits
  src/main/kotlin/com/relogging/server/domain/plogging/controller/PloggingEventController.kt
  src/main/kotlin/com/relogging/server/domain/plogging/repository/PloggingEventRepository.kt
  src/main/kotlin/com/relogging/server/domain/plogging/service/PloggingEventService.kt
  src/main/kotlin/com/relogging/server/domain/plogging/service/PloggingEventServiceImpl.kt
Labels: feat
