Repository Re-logging/server, pull requests merged in 2024-10, with the labels that each got.

#39 add: @EnableScheduling 추
  src/main/kotlin/com/relogging/server/global/config/JpaConfig.kt
Labels: fix

#42 feat: 이전 글 다음 글 뉴스 상세 조회 구현
  src/main/kotlin/com/relogging/server/controller/NewsArticleController.kt
  src/main/kotlin/com/relogging/server/repository/NewsArticleRepository.kt
  src/main/kotlin/com/relogging/server/service/newsArticle/NewsArticleService.kt
  src/main/kotlin/com/relogging/server/service/newsArticle/NewsArticleServiceImpl.kt
Labels: feat

#43 chore: 뉴스 조회 시 최신순 정렬
  src/main/kotlin/com/relogging/server/controller/AdminController.kt
  src/main/kotlin/com/relogging/server/repository/NewsArticleRepository.kt
  src/main/kotlin/com/relogging/server/service/crawling/CrawlingService.kt
  src/main/kotlin/com/relogging/server/service/crawling/NewsArticleCrawlingServiceImpl.kt
  src/main/kotlin/com/relogging/server/service/newsArticle/NewsArticleServiceImpl.kt
Labels: chore

#44 Feat/28 plogging event
  src/main/kotlin/com/relogging/server/controller/AdminController.kt
  src/main/kotlin/com/relogging/server/convertor/ImageConvertor.kt
  src/main/kotlin/com/relogging/server/convertor/PloggingEventConvertor.kt
  src/main/kotlin/com/relogging/server/dto/request/PloggingEventRequest.kt
  src/main/kotlin/com/relogging/server/entity/PloggingEvent.kt
  src/main/kotlin/com/relogging/server/global/exception/GlobalErrorCode.kt
  src/main/kotlin/com/relogging/server/service/crawling/CrawlingService.kt
  src/main/kotlin/com/relogging/server/service/crawling/NewsArticleCrawlingServiceImpl.kt
  src/main/kotlin/com/relogging/server/service/crawling/PloggingEventCrawlingServiceImpl.kt
  src/main/kotlin/com/relogging/server/service/image/ImageService.kt
  src/main/kotlin/com/relogging/server/service/image/ImageServiceImpl.kt
  src/main/kotlin/com/relogging/server/service/newsArticle/NewsArticleServiceImpl.kt
  src/main/kotlin/com/relogging/server/service/plogging/PloggingEventService.kt
  src/main/kotlin/com/relogging/server/service/plogging/PloggingEventServiceImpl.kt
  src/main/resources/application.yml
Labels: feat, refactor

#46 feat: prev plogging event, next plogging event
  src/main/kotlin/com/relogging/server/controller/PloggingEventController.kt
  src/main/kotlin/com/relogging/server/repository/PloggingEventRepository.kt
  src/main/kotlin/com/relogging/server/service/plogging/PloggingEventService.kt
  src/main/kotlin/com/relogging/server/service/plogging/PloggingEventServiceImpl.kt
Labels: feat

#47 add: 뉴스 상세 조회 시 이미지 url 추가
  src/main/kotlin/com/relogging/server/convertor/NewsArticleConvertor.kt
  src/main/kotlin/com/relogging/server/dto/response/NewsArticleResponse.kt
Labels: add

#55 domain: 유저 및 크루 엔티티 클래스 구현
  src/main/kotlin/com/relogging/server/domain/crew/entity/Crew.kt
  src/main/kotlin/com/relogging/server/domain/crew/entity/CrewApplication.kt
  src/main/kotlin/com/relogging/server/domain/crew/entity/CrewMember.kt
  src/main/kotlin/com/relogging/server/domain/user/entity/User.kt
Labels: feat

#56 refactor: ktlint
  src/main/kotlin/com/relogging/server/domain/crew/entity/Crew.kt
Labels: refactor

#59 Feat/58 plogging meetup
  .github/workflows/dev_ci_cd.yml
  .github/workflows/main_ci_cd.yml
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/controller/PloggingMeetupController.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/dto/PloggingMeetupConverter.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/dto/PloggingMeetupRequest.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/dto/PloggingMeetupResponse.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/entity/PloggingMeetup.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/repository/PloggingMeetupRepository.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/service/PloggingMeetupService.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/service/PloggingMeetupServiceImpl.kt
  src/main/kotlin/com/relogging/server/global/exception/GlobalErrorCode.kt
  src/main/kotlin/com/relogging/server/infrastructure/admin/controller/AdminController.kt
  src/main/resources/application.yml
Labels: feat

#62 Feat/52 oauth jwt
  build.gradle.kts
  docker-compose.yml
  src/main/kotlin/com/relogging/server/domain/user/entity/User.kt
  src/main/kotlin/com/relogging/server/domain/user/repository/UserRepository.kt
  src/main/kotlin/com/relogging/server/domain/user/service/UserService.kt
  src/main/kotlin/com/relogging/server/domain/user/service/UserServiceImpl.kt
  src/main/kotlin/com/relogging/server/global/config/JacksonConfig.kt
  src/main/kotlin/com/relogging/server/global/config/RedisConfig.kt
  src/main/kotlin/com/relogging/server/global/exception/GlobalErrorCode.kt
  src/main/kotlin/com/relogging/server/redis/entity/RefreshToken.kt
  src/main/kotlin/com/relogging/server/redis/repository/RefreshTokenRepository.kt
  src/main/kotlin/com/relogging/server/redis/service/RefreshTokenService.kt
  src/main/kotlin/com/relogging/server/redis/service/RefreshTokenServiceImpl.kt
  src/main/kotlin/com/relogging/server/security/config/SecurityConfig.kt
  src/main/kotlin/com/relogging/server/security/details/PrincipalDetails.kt
  src/main/kotlin/com/relogging/server/security/filter/AuthenticationExceptionFilter.kt
  src/main/kotlin/com/relogging/server/security/jwt/filter/JwtFilter.kt
  src/main/kotlin/com/relogging/server/security/jwt/provider/TokenProvider.kt
  src/main/kotlin/com/relogging/server/security/oauth/handler/OAuthAuthenticationSuccessHandler.kt
  src/main/kotlin/com/relogging/server/security/oauth/provider/GoogleUserInfo.kt
  src/main/kotlin/com/relogging/server/security/oauth/provider/KakaoUserInfo.kt
  src/main/kotlin/com/relogging/server/security/oauth/provider/OAuthUserInfo.kt
  src/main/kotlin/com/relogging/server/security/oauth/service/CustomOAuthUserService.kt
  src/main/kotlin/com/relogging/server/security/service/PrincipalDetailsService.kt
  src/main/resources/application.yml
Labels: feat
