Repository Re-logging/server, pull requests merged in 2024-12, with the labels that each got.

#92 Release 1.0.0
  .github/PULL_REQUEST_TEMPLATE.md
Labels: release

#96 feat: 이미지 없을 때 랜덤 이미지 저장
  src/main/kotlin/com/relogging/server/domain/crew/service/CrewServiceImpl.kt
  src/main/kotlin/com/relogging/server/domain/plogging/service/PloggingEventServiceImpl.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/dto/PloggingMeetupConverter.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/dto/PloggingMeetupRequest.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/dto/PloggingMeetupResponse.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/entity/PloggingMeetup.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/service/PloggingMeetupServiceImpl.kt
  src/main/kotlin/com/relogging/server/global/util/RandomImage.kt
  src/main/kotlin/com/relogging/server/infrastructure/scraping/service/NewsArticleNewsArticleScrapingServiceImpl.kt
Labels: feat

#99 Feat/98 report
  src/main/kotlin/com/relogging/server/domain/comment/controller/PloggingMeetupCommentController.kt
  src/main/kotlin/com/relogging/server/domain/comment/controller/ReportCommentController.kt
  src/main/kotlin/com/relogging/server/domain/comment/dto/CommentConverter.kt
  src/main/kotlin/com/relogging/server/domain/comment/dto/CommentRequest.kt
  src/main/kotlin/com/relogging/server/domain/comment/entity/Report.kt
  src/main/kotlin/com/relogging/server/domain/comment/repository/ReportRepository.kt
  src/main/kotlin/com/relogging/server/domain/comment/service/ReportCommentService.kt
  src/main/kotlin/com/relogging/server/domain/comment/service/ReportCommentServiceImpl.kt
Labels: feat

#101 chore: feat 93 롤백
  src/main/kotlin/com/relogging/server/domain/crew/service/CrewServiceImpl.kt
  src/main/kotlin/com/relogging/server/domain/plogging/service/PloggingEventServiceImpl.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/dto/PloggingMeetupConverter.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/dto/PloggingMeetupResponse.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/entity/PloggingMeetup.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/service/PloggingMeetupServiceImpl.kt
  src/main/kotlin/com/relogging/server/global/util/RandomImage.kt
  src/main/kotlin/com/relogging/server/infrastructure/scraping/service/NewsArticleScrapingServiceImpl.kt
Labels: chore

#102 Feat/73 sort and filtering
  build.gradle.kts
  src/main/kotlin/com/relogging/server/domain/comment/controller/ReportCommentController.kt
  src/main/kotlin/com/relogging/server/domain/plogging/PloggingEventSortType.kt
  src/main/kotlin/com/relogging/server/domain/plogging/controller/PloggingEventController.kt
  src/main/kotlin/com/relogging/server/domain/plogging/repository/PloggingEventCustomRepository.kt
  src/main/kotlin/com/relogging/server/domain/plogging/repository/PloggingEventCustomRepositoryImpl.kt
  src/main/kotlin/com/relogging/server/domain/plogging/repository/PloggingEventRepository.kt
  src/main/kotlin/com/relogging/server/domain/plogging/service/PloggingEventService.kt
  src/main/kotlin/com/relogging/server/domain/plogging/service/PloggingEventServiceImpl.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/PloggingMeetupSortType.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/controller/PloggingMeetupController.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/dto/PloggingMeetupConverter.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/entity/PloggingMeetup.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/repository/PloggingMeetupCustomRepository.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/repository/PloggingMeetupCustomRepositoryImpl.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/repository/PloggingMeetupRepository.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/service/PloggingMeetupService.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/service/PloggingMeetupServiceImpl.kt
  src/main/kotlin/com/relogging/server/global/config/QuerydslConfig.kt
  src/main/kotlin/com/relogging/server/infrastructure/kakao/server/KakaoService.kt
Labels: feat

#103 chore: 기본 정렬 END_DATE
  src/main/kotlin/com/relogging/server/domain/plogging/controller/PloggingEventController.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/controller/PloggingMeetupController.kt
Labels: chore

#104 Feat/94 kakao message
  .github/workflows/dev_ci_cd.yml
  .github/workflows/main_ci_cd.yml
  src/main/kotlin/com/relogging/server/global/exception/GlobalErrorCode.kt
  src/main/kotlin/com/relogging/server/infrastructure/admin/controller/AdminController.kt
  src/main/kotlin/com/relogging/server/infrastructure/admin/dto/AdminConverter.kt
  src/main/kotlin/com/relogging/server/infrastructure/admin/dto/AdminRequest.kt
  src/main/kotlin/com/relogging/server/infrastructure/admin/entity/Admin.kt
  src/main/kotlin/com/relogging/server/infrastructure/admin/repository/AdminRepository.kt
  src/main/kotlin/com/relogging/server/infrastructure/admin/service/AdminAuthService.kt
  src/main/kotlin/com/relogging/server/infrastructure/admin/service/AdminAuthServiceImpl.kt
  src/main/kotlin/com/relogging/server/infrastructure/admin/service/AdminService.kt
  src/main/kotlin/com/relogging/server/infrastructure/admin/service/AdminServiceImpl.kt
  src/main/kotlin/com/relogging/server/infrastructure/kakao/dto/KakaoTokenResponse.kt
  src/main/kotlin/com/relogging/server/infrastructure/kakao/server/KakaoService.kt
  src/main/kotlin/com/relogging/server/infrastructure/kakao/service/KakaoMessageService.kt
  src/main/kotlin/com/relogging/server/infrastructure/kakao/service/KakaoMessageServiceImpl.kt
  src/main/kotlin/com/relogging/server/infrastructure/kakao/template/KakaoTemplate.kt
  src/main/kotlin/com/relogging/server/infrastructure/scheduler/AdminScheduler.kt
  src/main/resources/application.yml
Labels: feat

#105 Release 1.1.0
  .github/workflows/dev_ci_cd.yml
  .github/workflows/main_ci_cd.yml
  build.gradle.kts
  src/main/kotlin/com/relogging/server/domain/comment/controller/PloggingMeetupCommentController.kt
  src/main/kotlin/com/relogging/server/domain/comment/controller/ReportCommentController.kt
  src/main/kotlin/com/relogging/server/domain/comment/dto/CommentConverter.kt
  src/main/kotlin/com/relogging/server/domain/comment/dto/CommentRequest.kt
  src/main/kotlin/com/relogging/server/domain/comment/entity/Report.kt
  src/main/kotlin/com/relogging/server/domain/comment/repository/ReportRepository.kt
  src/main/kotlin/com/relogging/server/domain/comment/service/ReportCommentService.kt
  src/main/kotlin/com/relogging/server/domain/comment/service/ReportCommentServiceImpl.kt
  src/main/kotlin/com/relogging/server/domain/crew/service/CrewServiceImpl.kt
  src/main/kotlin/com/relogging/server/domain/plogging/PloggingEventSortType.kt
  src/main/kotlin/com/relogging/server/domain/plogging/controller/PloggingEventController.kt
  src/main/kotlin/com/relogging/server/domain/plogging/repository/PloggingEventCustomRepository.kt
  src/main/kotlin/com/relogging/server/domain/plogging/repository/PloggingEventCustomRepositoryImpl.kt
  src/main/kotlin/com/relogging/server/domain/plogging/repository/PloggingEventRepository.kt
  src/main/kotlin/com/relogging/server/domain/plogging/service/PloggingEventService.kt
  src/main/kotlin/com/relogging/server/domain/plogging/service/PloggingEventServiceImpl.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/PloggingMeetupSortType.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/controller/PloggingMeetupController.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/dto/PloggingMeetupConverter.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/dto/PloggingMeetupRequest.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/entity/PloggingMeetup.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/repository/PloggingMeetupCustomRepository.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/repository/PloggingMeetupCustomRepositoryImpl.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/repository/PloggingMeetupRepository.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/service/PloggingMeetupService.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/service/PloggingMeetupServiceImpl.kt
  src/main/kotlin/com/relogging/server/global/config/QuerydslConfig.kt
  src/main/kotlin/com/relogging/server/global/exception/GlobalErrorCode.kt
  src/main/kotlin/com/relogging/server/infrastructure/admin/controller/AdminController.kt
  src/main/kotlin/com/relogging/server/infrastructure/admin/dto/AdminConverter.kt
  src/main/kotlin/com/relogging/server/infrastructure/admin/dto/AdminRequest.kt
  src/main/kotlin/com/relogging/server/infrastructure/admin/entity/Admin.kt
  src/main/kotlin/com/relogging/server/infrastructure/admin/repository/AdminRepository.kt
  src/main/kotlin/com/relogging/server/infrastructure/admin/service/AdminAuthService.kt
  src/main/kotlin/com/relogging/server/infrastructure/admin/service/AdminAuthServiceImpl.kt
  src/main/kotlin/com/relogging/server/infrastructure/admin/service/AdminService.kt
  src/main/kotlin/com/relogging/server/infrastructure/admin/service/AdminServiceImpl.kt
  src/main/kotlin/com/relogging/server/infrastructure/kakao/dto/KakaoTokenResponse.kt
  src/main/kotlin/com/relogging/server/infrastructure/kakao/service/KakaoMessageService.kt
  src/main/kotlin/com/relogging/server/infrastructure/kakao/service/KakaoMessageServiceImpl.kt
  src/main/kotlin/com/relogging/server/infrastructure/kakao/template/KakaoTemplate.kt
  src/main/kotlin/com/relogging/server/infrastructure/scheduler/AdminScheduler.kt
  src/main/kotlin/com/relogging/server/infrastructure/scraping/service/NewsArticleScrapingServiceImpl.kt
  src/main/resources/application.yml
Labels: release

#106 Feat/94 kakao message
  src/main/kotlin/com/relogging/server/infrastructure/scheduler/AdminScheduler.kt
Labels: fix

#107 Release 1.1.1
  src/main/kotlin/com/relogging/server/infrastructure/scheduler/AdminScheduler.kt
Labels: release

#110 fix: 어드민 스케줄러 오류처리
  src/main/kotlin/com/relogging/server/infrastructure/scheduler/AdminScheduler.kt
Labels: fix

#111 Release 1.1.2
  src/main/kotlin/com/relogging/server/infrastructure/scheduler/AdminScheduler.kt
Labels: release

#112 Fix/admin scheduler
  src/main/kotlin/com/relogging/server/infrastructure/admin/controller/AdminController.kt
  src/main/kotlin/com/relogging/server/infrastructure/scheduler/AdminScheduler.kt
Labels: fix

#115 Feat/114 meetup update delete
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/controller/PloggingMeetupController.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/dto/PloggingMeetupConverter.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/dto/PloggingMeetupRequest.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/entity/PloggingMeetup.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/repository/PloggingMeetupRepository.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/service/PloggingMeetupService.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/service/PloggingMeetupServiceImpl.kt
  src/main/kotlin/com/relogging/server/global/exception/GlobalErrorCode.kt
Labels: feat
