Repository Re-logging/server, pull requests merged in 2025-02, with the labels that each got.

#126 fix: notificaiton type
  src/main/kotlin/com/relogging/server/domain/notification/dto/NotificationConverter.kt
  src/main/kotlin/com/relogging/server/domain/notification/dto/NotificationResponse.kt
Labels: fix

#124 Feat/121 plogging data coordinate
  .github/workflows/dev_ci_cd.yml
  .github/workflows/main_ci_cd.yml
  build.gradle.kts
  src/main/kotlin/com/relogging/server/domain/plogging/dto/PloggingEventConverter.kt
  src/main/kotlin/com/relogging/server/domain/plogging/dto/PloggingEventRequest.kt
  src/main/kotlin/com/relogging/server/domain/plogging/dto/PloggingEventResponse.kt
  src/main/kotlin/com/relogging/server/domain/plogging/entity/PloggingEvent.kt
  src/main/kotlin/com/relogging/server/domain/plogging/service/PloggingEventServiceImpl.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/dto/PloggingMeetupConverter.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/dto/PloggingMeetupRequest.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/dto/PloggingMeetupResponse.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/entity/PloggingMeetup.kt
  src/main/kotlin/com/relogging/server/domain/utils/coordinate/Coordinate.kt
  src/main/kotlin/com/relogging/server/domain/utils/coordinate/dto/CoordinateConverter.kt
  src/main/kotlin/com/relogging/server/domain/utils/coordinate/dto/CoordinateRequest.kt
  src/main/kotlin/com/relogging/server/domain/utils/coordinate/dto/CoordinateResponse.kt
  src/main/kotlin/com/relogging/server/global/exception/GlobalErrorCode.kt
  src/main/kotlin/com/relogging/server/infrastructure/admin/controller/AdminController.kt
  src/main/kotlin/com/relogging/server/infrastructure/naver/dto/NaverGeocodingResponse.kt
  src/main/kotlin/com/relogging/server/infrastructure/naver/service/NaverGeocodingGeocodingServiceImpl.kt
  src/main/kotlin/com/relogging/server/infrastructure/naver/service/NaverGeocodingService.kt
  src/main/resources/application.yml
Labels: feat

#127 fix: 뉴스 스크래핑 및 ai 요약 예외처리
  src/main/kotlin/com/relogging/server/domain/newsArticle/entity/NewsArticle.kt
  src/main/kotlin/com/relogging/server/infrastructure/scheduler/NewsArticleScrapingScheduler.kt
Labels: fix

#128 Release 1.2.0
  .github/workflows/dev_ci_cd.yml
  .github/workflows/main_ci_cd.yml
  build.gradle.kts
  src/main/kotlin/com/relogging/server/domain/comment/controller/PloggingEventCommentController.kt
  src/main/kotlin/com/relogging/server/domain/comment/controller/PloggingMeetupCommentController.kt
  src/main/kotlin/com/relogging/server/domain/comment/dto/CommentConverter.kt
  src/main/kotlin/com/relogging/server/domain/comment/entity/Comment.kt
  src/main/kotlin/com/relogging/server/domain/comment/service/PloggingEventCommentService.kt
  src/main/kotlin/com/relogging/server/domain/comment/service/PloggingEventCommentServiceImpl.kt
  src/main/kotlin/com/relogging/server/domain/comment/service/PloggingMeetupCommentService.kt
  src/main/kotlin/com/relogging/server/domain/comment/service/PloggingMeetupCommentServiceImpl.kt
  src/main/kotlin/com/relogging/server/domain/newsArticle/entity/NewsArticle.kt
  src/main/kotlin/com/relogging/server/domain/notification/annotation/CommentNotification.kt
  src/main/kotlin/com/relogging/server/domain/notification/annotation/ReplyNotification.kt
  src/main/kotlin/com/relogging/server/domain/notification/aspect/NotificationAspect.kt
  src/main/kotlin/com/relogging/server/domain/notification/controller/NotificationController.kt
  src/main/kotlin/com/relogging/server/domain/notification/dto/CommentNotificationData.kt
  src/main/kotlin/com/relogging/server/domain/notification/dto/NotificationConverter.kt
  src/main/kotlin/com/relogging/server/domain/notification/dto/NotificationResponse.kt
  src/main/kotlin/com/relogging/server/domain/notification/dto/ReplyNotificationData.kt
  src/main/kotlin/com/relogging/server/domain/notification/entity/Notification.kt
  src/main/kotlin/com/relogging/server/domain/notification/repository/NotificationRepository.kt
  src/main/kotlin/com/relogging/server/domain/notification/service/NotificationService.kt
  src/main/kotlin/com/relogging/server/domain/notification/service/NotificationServiceImpl.kt
  src/main/kotlin/com/relogging/server/domain/plogging/controller/PloggingEventController.kt
  src/main/kotlin/com/relogging/server/domain/plogging/dto/PloggingEventConverter.kt
  src/main/kotlin/com/relogging/server/domain/plogging/dto/PloggingEventRequest.kt
  src/main/kotlin/com/relogging/server/domain/plogging/dto/PloggingEventResponse.kt
  src/main/kotlin/com/relogging/server/domain/plogging/entity/PloggingEvent.kt
  src/main/kotlin/com/relogging/server/domain/plogging/service/PloggingEventServiceImpl.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/controller/PloggingMeetupController.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/dto/PloggingMeetupConverter.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/dto/PloggingMeetupRequest.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/dto/PloggingMeetupResponse.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/entity/PloggingMeetup.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/repository/PloggingMeetupRepository.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/service/PloggingMeetupService.kt
  src/main/kotlin/com/relogging/server/domain/ploggingMeetup/service/PloggingMeetupServiceImpl.kt
  src/main/kotlin/com/relogging/server/domain/user/entity/User.kt
  src/main/kotlin/com/relogging/server/domain/utils/coordinate/Coordinate.kt
  src/main/kotlin/com/relogging/server/domain/utils/coordinate/dto/CoordinateConverter.kt
  src/main/kotlin/com/relogging/server/domain/utils/coordinate/dto/CoordinateRequest.kt
  src/main/kotlin/com/relogging/server/domain/utils/coordinate/dto/CoordinateResponse.kt
  src/main/kotlin/com/relogging/server/global/config/AopConfig.kt
  src/main/kotlin/com/relogging/server/global/exception/GlobalErrorCode.kt
  src/main/kotlin/com/relogging/server/infrastructure/admin/controller/AdminController.kt
  src/main/kotlin/com/relogging/server/infrastructure/naver/dto/NaverGeocodingResponse.kt
  src/main/kotlin/com/relogging/server/infrastructure/naver/service/NaverGeocodingGeocodingServiceImpl.kt
  src/main/kotlin/com/relogging/server/infrastructure/naver/service/NaverGeocodingService.kt
  src/main/kotlin/com/relogging/server/infrastructure/scheduler/AdminScheduler.kt
  src/main/kotlin/com/relogging/server/infrastructure/scheduler/NewsArticleScrapingScheduler.kt
  src/main/kotlin/com/relogging/server/infrastructure/sse/controller/SseController.kt
  src/main/kotlin/com/relogging/server/infrastructure/sse/repository/SseRepository.kt
  src/main/kotlin/com/relogging/server/infrastructure/sse/repository/SseRepositoryImpl.kt
  src/main/kotlin/com/relogging/server/infrastructure/sse/service/SseService.kt
  src/main/kotlin/com/relogging/server/infrastructure/sse/service/SseServiceImpl.kt
  src/main/resources/application.yml
Labels: release
